import Footer from '@components/Footer'
import Navigation from '@components/Navigation'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
  variable: '--font-inter',
  preload: true,
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <div className="bg-grid"></div>
        <Navigation />
        <main className="container page">{children}</main>
        <Footer />
      </body>
    </html>
  )
}

export default RootLayout
